// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

/*
Package org_it_andreagrandi_protorabbit_user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	User
*/
package org_it_andreagrandi_protorabbit_user

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type User struct {
	FirstName        *string `protobuf:"bytes,1,req,name=firstName" json:"firstName,omitempty"`
	LastName         *string `protobuf:"bytes,2,req,name=lastName" json:"lastName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func (m *User) GetFirstName() string {
	if m != nil && m.FirstName != nil {
		return *m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil && m.LastName != nil {
		return *m.LastName
	}
	return ""
}

func init() {
}
